SystemOrganization addCategory: #'Moose-Camel-Comments'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Model'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Model - Comment'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Model - Environment'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Model - Reference'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Model - Text'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Parser'!
SystemOrganization addCategory: #'Moose-Camel-Comments-Uncategorized'!
