as yet unclassified
desireVerbs
	"a verb that expresses the class’s desire"
	
	^	{'aim' .'anticipate'.'aspire' .'assume' .'attempt' .'believe' .'can' .'demand' .'desire' .'expect' .'expectation' .'goal' .'hope'.'imagine'.'intend'.'intent'.'intention'.'interested'.'like'.'must'.'need'.'objective'.'ought'.'picture'.'plan'.'prefer'.'presume'.'purpose'.'require'.'represent'.'responsibile'.'seek'.'should'.'strive'.'suppose'.'think'.'try'.'want'.'wish'} 