as yet unclassified
systemSubjects
"potential subjects of a sentence"

	^	{'algorithm'.'application'.'array'.'boolean'.'button'.'character'.'class'.'client'.'code'.'column'.'compiler'.'console'.'Transcript'.'data'.'database'.'environment'.'float'.'function'.'instance'.'integer'.'interface'.'it'.'item'.'library'.'loop'.'method'.'message'.'object'.'output'.'package'.'page'.'platform'.'environment'.'process'.'program'.'result'.'row'.'script'.'server'.'set'.'string'.'structure'.'system'.'table'.'thread'.'type'.'value'.'variable'.'view'.'class'.'variable'.'package'.'namespace'.'exception'.'module'.'function'.'bookmark'.'enum'.'UI'.'panel'.'icon'.'box'.'window'.'tooltip'.'notification'.'options'.'shortcut'.'slider'.'color'.'menu'.'dialog'.'taskbar'.'wizard' }