"
I store metadata for this package. These meta data are used by other tools such as the SmalllintManifestChecker and the critics Browser
"
Class {
	#name : #ManifestMooseCamelComments,
	#superclass : #PackageManifest,
	#category : 'Moose-Camel-Comments'
}

{ #category : #'code-critics' }
ManifestMooseCamelComments class >> ruleRBAssignmentInIfTrueRuleV1FalsePositive [
	^ #(#(#(#RGClassDefinition #(#MccCommentLinguisticFeatures)) #'2019-08-27T09:53:58.436093+02:00') )
]

{ #category : #'code-critics' }
ManifestMooseCamelComments class >> ruleReInspectorPresentationsNonBlockSetupV1FalsePositive [
	^ #(#(#(#RGPackage #(#'Moose-Camel-Comments')) #'2018-10-29T22:42:51.58859+01:00') )
]
