Class {
	#name : #MccTextCommentExample,
	#superclass : #Object,
	#category : #'Moose-Camel-Comments-Examples-Artefacts'
}

{ #category : #'as yet unclassified' }
MccTextCommentExample >> aTextComment [
<gtExample>
^ MccTextComment of: 'I am just a textual comment that does not belong to anything. I am generally created form external environment CSV of class and its comments. If I am loaded with class information, I know my class using className.
[[[
	MccTextComment of: ''Number holds the most general methods for dealing with numbers.''
]]]'.
]
